language: python
python:
- '2.7'
sudo: required
env:
  global: 
  - USER_REPO=$(echo $TRAVIS_REPO_SLUG | cut -f -1 -d /)
services:
- docker
before_install:
- docker pull f5devcentral/containthedocs
install: true
script:
 - ./scripts/docker-docs.sh make -C docs/ html
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
